version: '3.8'

services:
  php-upload:
    image: php:7.4-apache
    container_name: php-upload
    ports:
      - "8888:80"
    volumes:
      - .:/var/www/html
      - ./custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    entrypoint: ["sh", "-c", "mkdir -p /var/www/html/uploads && chown -R www-data:www-data /var/www/html/uploads && apache2-foreground"]
